Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ming/Documents/TieComm/main.py", line 175, in <module>
    main(args)
  File "/Users/ming/Documents/TieComm/main.py", line 113, in main
    log = runner.train_batch(epoch_size)
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 38, in train_batch
    train_log = self.compute_grad(batch_data)
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 138, in compute_grad
    returns = self._compute_returns(rewards, episode_masks, values[:-1])
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 115, in _compute_returns
    ret = returns[0] * self.gamma * (1 - done.unsqueeze(1)) + rew
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)